//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_22._101_Dmitriev_PR5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsiblePerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResponsiblePerson()
        {
            this.ObjectInspection = new HashSet<ObjectInspection>();
        }
    
        public int ResponsiblePerson_ID { get; set; }
        public int ResponsiblePersonType_ID { get; set; }
        public int Object_ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string FatherName { get; set; }
        public string PhoneNumber { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual Object Object { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjectInspection> ObjectInspection { get; set; }
        public virtual ResponsiblePersonType ResponsiblePersonType { get; set; }
    }
}
